# Generated by Django 4.2 on 2024-09-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfilePics',
            new_name='ProfilePic',
        ),
    ]
