# Generated by Django 5.1.1 on 2024-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='usage',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
