# Generated by Django 4.2 on 2024-09-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('laugh', 'Laugh'), ('sad', 'Sad'), ('angry', 'Angry')], default='like', max_length=10),
        ),
    ]
